apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: euyjd44f7-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: euyjd44f7-python 
  name: euyjd44f7-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: euyjd44f7-python 
